#!/usr/bin/python

print('How many minutes?')
m = input()
print('and how many seconds?')
s = input()
print('')
print(str(m) + ' minutes, and ' + str(s) + ''' seconds: ''' + str(m) + ''':''' + str(s))
print('')
print('60 seconds in a minute...')
print('')
print('60 * ' + str(m))
ms = 60 * int(m)
print('')
print(str(ms) + ' seconds from the ' + str(m) + ' minutes,')
print('and ' + str(s) + ' more seconds to add on...')
t = int(ms) + int(s)
print('')
print(str(ms) + ''' + ''' + str(s))
#end = input()
ot = (60 * int(m)) + int(s)
print('')
print('...')
print('..')
print('.')
print('')
print(str(t) + ' seconds')
print('')
print('Thank you!')
